// <auto-generated />
using System;
using ClubsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubsApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104105807_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClubsApi.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ClubsApi.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contact")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Teknoloji",
                            Contact = "ai@okul.com",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "AI projeleri ve arastirmalar.",
                            Name = "Yapay Zeka Kulubu",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Teknoloji",
                            Contact = "security@okul.com",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CTF ve siber savunma egitimleri.",
                            Name = "Siber Guvenlik Kulubu",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Is ve Girisim",
                            Contact = "giris@okul.com",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Startup ve networking etkinlikleri.",
                            Name = "Girisimcilik Kulubu",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.ClubAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoleInClub")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClubId", "UserId")
                        .IsUnique();

                    b.ToTable("club_admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleInClub = "Owner",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleInClub = "Owner",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.ClubMembershipApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClubId", "UserId")
                        .IsUnique();

                    b.ToTable("club_membership_applications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Seeded membership",
                            ReviewedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 60,
                            ClubId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni baslayanlar icin temel AI workshop.",
                            EndAt = new DateTime(2025, 2, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "M1 Konferans Salonu",
                            StartAt = new DateTime(2025, 2, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "AI 101 Atolyesi"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            ClubId = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ML model performansi ve metrikler.",
                            EndAt = new DateTime(2025, 2, 18, 19, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Lab 3",
                            StartAt = new DateTime(2025, 2, 18, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "Model Degerlendirme Semineri"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            ClubId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Takim olusturma ve alistirmalar.",
                            EndAt = new DateTime(2025, 2, 12, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Siber Lab",
                            StartAt = new DateTime(2025, 2, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "CTF Hazirlik Oturumu"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 120,
                            ClubId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fikirlerinizi juriye sunun.",
                            EndAt = new DateTime(2025, 2, 20, 21, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Etkinlik Salonu",
                            StartAt = new DateTime(2025, 2, 20, 18, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "Startup Pitch Night"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30,
                            ClubId = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yatirimci bulusmasi ve mentorluk.",
                            EndAt = new DateTime(2025, 2, 25, 17, 30, 0, 0, DateTimeKind.Utc),
                            Location = "Kulupler Binasi",
                            StartAt = new DateTime(2025, 2, 25, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "Yatirimci ile Kahve"
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Registered");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("event_registrations", (string)null);
                });

            modelBuilder.Entity("ClubsApi.Models.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserId");

                    b.ToTable("student_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Bio = "Yapay zeka ve topluluk etkinlikleriyle ilgileniyor.",
                            Department = "Bilgisayar Muhendisligi",
                            Faculty = "Muhendislik"
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@bugbusters.dev",
                            Name = "Ayse Demir",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuusvjCjxykWM6EVr4NLmYOZDEUJzz8Mcm",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@bugbusters.dev",
                            Name = "Ali Yilmaz",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuunexzIc3x8I4UQSfyinzLbbkD0PvhD6a",
                            Role = "ClubAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@bugbusters.dev",
                            Name = "Ece Koc",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuunexzIc3x8I4UQSfyinzLbbkD0PvhD6a",
                            Role = "ClubAdmin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sks@bugbusters.dev",
                            Name = "Sks Yetkilisi",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuutK6kgbr7Fw8OIjF7TSn68Opi3gTMwfq",
                            Role = "SksAdmin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ops@bugbusters.dev",
                            Name = "Ops Admin",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuuUV5XOpUP0aNxeeIpIwHSsKodZk708Ru",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("ClubsApi.Models.AuditLog", b =>
                {
                    b.HasOne("ClubsApi.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ClubsApi.Models.ClubAdmin", b =>
                {
                    b.HasOne("ClubsApi.Models.Club", "Club")
                        .WithMany("ClubAdmins")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubsApi.Models.User", "User")
                        .WithMany("ClubAdminRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubsApi.Models.ClubMembershipApplication", b =>
                {
                    b.HasOne("ClubsApi.Models.Club", "Club")
                        .WithMany("ClubMembershipApplications")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubsApi.Models.User", "User")
                        .WithMany("ClubMembershipApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubsApi.Models.Event", b =>
                {
                    b.HasOne("ClubsApi.Models.Club", "Club")
                        .WithMany("Events")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubsApi.Models.EventRegistration", b =>
                {
                    b.HasOne("ClubsApi.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubsApi.Models.User", "User")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubsApi.Models.StudentProfile", b =>
                {
                    b.HasOne("ClubsApi.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("ClubsApi.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubsApi.Models.Club", b =>
                {
                    b.Navigation("ClubAdmins");

                    b.Navigation("ClubMembershipApplications");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("ClubsApi.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("ClubsApi.Models.User", b =>
                {
                    b.Navigation("ClubAdminRoles");

                    b.Navigation("ClubMembershipApplications");

                    b.Navigation("EventRegistrations");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
